import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google';
import Header from "@/components/shared/header";
import { cn } from "@/lib/utils";

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "NEXTLIB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(font.className, 'bg-black')}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
